stages:
  - build
  - push
  - deploy

variables:
  DOCKER_IMAGE: 'adityajain0127/nodejs-todo_node-tode-app:latest'

# Job to build the Docker image
build:
  stage: build
  script:
    - echo "Cloning the repository..."
    - git clone https://github.com/ADITYA2777/node-todo-task-03.git
    - cd node-todo-task-03
    - echo "Building the Docker image..."
    - docker build -t $DOCKER_IMAGE .
  only:
    - main  # Trigger this job only on the main branch

# Job to push the Docker image to Docker Hub
push:
  stage: push
  script:
    - echo "Logging in to Docker Hub..."
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - echo "Pushing the Docker image to Docker Hub..."
    - docker push $DOCKER_IMAGE
  only:
    - main  # Trigger this job only on the main branch

# Job to deploy the application using docker-compose
deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    - docker-compose down
    - docker-compose up -d
  only:
    - main  # Trigger this job only on the main branch
